#ifndef MESSAGECONSTANTS_H
#define MESSAGECONSTANTS_H

// Placeholder message length, that will be changed when we completed the whole message
const char MESSAGE_LENGTH_PLACEHOLDER[] = "000000000000";
const char SEGMENT_MESSAGE_HEADER_ID[] = "HNHBK";
const char SEGMENT_MESSAGE_HEADER_VERSION[] = "3";
const char SEGMENT_IDENTIFICATION_ID[] = "HKIDN";
const char SEGMENT_IDENTIFICATION_VERSION[] = "2";
const char SEGMENT_PROCESS_PREPARATION_ID[] = "HKVVB";
const char SEGMENT_PROCESS_PREPARATION_VERSION[] = "3";
const char SEGMENT_MESSAGE_TERMINATION_ID[] = "HNHBS";
const char SEGMENT_MESSAGE_TERMINATION_VERSION[] = "1";
const char SEGMENT_MESSAGE_FEEDBACK_ID[] = "HIRMG";
const char SEGMENT_MESSAGE_FEEDBACK_VERSION[] = "2";
const char SEGMENT_SEGMENT_FEEDBACK_ID[] = "HIRMS";
const char SEGMENT_SEGMENT_FEEDBACK_VERSION[] = "2";
const char SEGMENT_BANK_PARAMETER_ID[] = "HIBPA";
const char SEGMENT_BANK_PARAMETER_VERSION[] = "3";
const char SEGMENT_SECURITY_PROCEDURE_ID[] = "HISHV";
const char SEGMENT_SECURITY_PROCEDURE_VERSION[] = "3";
#endif // MESSAGECONSTANTS_H
